---
- name: Testing andrewrothstein.popeye
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'popeye --version'
      ansible.builtin.command: popeye version
      changed_when: false
      register: popeye_test_output
    - name: Output from 'popeye version'
      ansible.builtin.debug:
        msg: '{{ popeye_test_output.stdout }}'
