---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/popeye version
    register: popeye_test_output
  - name: popeye version
    debug:
      msg: '{{ popeye_test_output.stdout }}'
