---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Looking for install in {{ popeye_install_exe }}...
  become: true
  ansible.builtin.stat:
    path: '{{ popeye_install_exe }}'
  changed_when: false
  register: popeye_binary
- name: Downloading and installing popeye
  when: not popeye_binary.stat.exists
  block:
    - name: Downloading {{ popeye_url }} to {{ popeye_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ popeye_url }}'
        dest: '{{ popeye_tmp_archive }}'
        checksum: '{{ popeye_checksum }}'
        mode: '644'
    - name: Mkdir {{ popeye_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ popeye_install_dir }}'
        state: directory
        mode: '755'
    - name: Installing andrewrothstein.unarchivedeps
      ansible.builtin.include_role:
        name: andrewrothstein.unarchivedeps
    - name: Unarchive {{ popeye_tmp_archive }} to {{ popeye_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ popeye_tmp_archive }}'
        dest: '{{ popeye_install_dir }}'
        creates: '{{ popeye_install_exe }}'
  always:
    - name: Rm -f {{ popeye_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ popeye_tmp_archive }}'
        state: absent
- name: Linking {{ popeye_install_link }} to {{ popeye_install_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ popeye_install_exe }}'
    dest: '{{ popeye_install_link }}'
    state: link
